spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/food
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  cache:
    cache-names:
      - rate-limit-bucket
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    openai:
      api-key: 
      chat:
        options:
          model: gpt-4o

server:
  port: 9003
  servlet:
    context-path: /api

bucket4j:
  cache-to-use: jcache
  enabled: true
  filters:
    - cache-name: rate-limit-bucket
      url: .*
      rate-limits:
        - cache-key: getHeader("CF-Connecting-IP") # IP based filter (assumes you're using Cloudflare)
          bandwidths: # max 10 reqs per second
            - capacity: 100
              time: 10
              unit: seconds

